security:
    encoders:
        MD\Bundle\MDUserBundle\Entity\User:
            algorithm: bcrypt
            cost:      15
        Symfony\Component\Security\Core\User\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
      chain_provider:
        chain:
          providers: [in_memory, db]
      in_memory:
        memory:
            users:
              mickel:  { password: a761ce3a45d97e41840a788495e85a70d1bb3815 , roles: [ 'ROLE_SUPER_ADMIN' ] } 
      db:
        entity: 
          class: MDUserBundle:User 
          property: username

    firewalls:
      default:
        pattern:   ^/
        anonymous: ~
#        form_login: ~
        form_login:
          default_target_path: dashboard
        logout:
            target: login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }